// Code generated by thriftrw v1.0.0
// @generated

package hello

import (
	"errors"
	"fmt"
	"go.uber.org/thriftrw/wire"
	"strings"
)

type Hello_CallHome_Args struct {
	CallHome *CallHomeRequest `json:"callHome,omitempty"`
}

func (v *Hello_CallHome_Args) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.CallHome != nil {
		w, err = v.CallHome.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _CallHomeRequest_Read(w wire.Value) (*CallHomeRequest, error) {
	var v CallHomeRequest
	err := v.FromWire(w)
	return &v, err
}

func (v *Hello_CallHome_Args) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.CallHome, err = _CallHomeRequest_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (v *Hello_CallHome_Args) String() string {
	var fields [1]string
	i := 0
	if v.CallHome != nil {
		fields[i] = fmt.Sprintf("CallHome: %v", v.CallHome)
		i++
	}
	return fmt.Sprintf("Hello_CallHome_Args{%v}", strings.Join(fields[:i], ", "))
}

func (v *Hello_CallHome_Args) MethodName() string {
	return "callHome"
}

func (v *Hello_CallHome_Args) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

var Hello_CallHome_Helper = struct {
	Args           func(callHome *CallHomeRequest) *Hello_CallHome_Args
	IsException    func(error) bool
	WrapResponse   func(*CallHomeResponse, error) (*Hello_CallHome_Result, error)
	UnwrapResponse func(*Hello_CallHome_Result) (*CallHomeResponse, error)
}{}

func init() {
	Hello_CallHome_Helper.Args = func(callHome *CallHomeRequest) *Hello_CallHome_Args {
		return &Hello_CallHome_Args{CallHome: callHome}
	}
	Hello_CallHome_Helper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}
	Hello_CallHome_Helper.WrapResponse = func(success *CallHomeResponse, err error) (*Hello_CallHome_Result, error) {
		if err == nil {
			return &Hello_CallHome_Result{Success: success}, nil
		}
		return nil, err
	}
	Hello_CallHome_Helper.UnwrapResponse = func(result *Hello_CallHome_Result) (success *CallHomeResponse, err error) {
		if result.Success != nil {
			success = result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}

type Hello_CallHome_Result struct {
	Success *CallHomeResponse `json:"success,omitempty"`
}

func (v *Hello_CallHome_Result) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("Hello_CallHome_Result should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _CallHomeResponse_Read(w wire.Value) (*CallHomeResponse, error) {
	var v CallHomeResponse
	err := v.FromWire(w)
	return &v, err
}

func (v *Hello_CallHome_Result) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _CallHomeResponse_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("Hello_CallHome_Result should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *Hello_CallHome_Result) String() string {
	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}
	return fmt.Sprintf("Hello_CallHome_Result{%v}", strings.Join(fields[:i], ", "))
}

func (v *Hello_CallHome_Result) MethodName() string {
	return "callHome"
}

func (v *Hello_CallHome_Result) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}
