// Code generated by thriftrw v1.0.0
// @generated

package hello

import "go.uber.org/thriftrw/version"

func init() {
	version.CheckCompatWithGeneratedCodeAt("1.0.0", "github.com/breerly/hellodi/hello")
}
