// Code generated by thriftrw-plugin-yarpc
// @generated

package hellotest

import (
	"context"
	"go.uber.org/yarpc"
	"github.com/breerly/hellodi/hello"
	"github.com/golang/mock/gomock"
	"github.com/breerly/hellodi/hello/helloclient"
)

// MockClient implements a gomock-compatible mock client for service
// Hello.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *_MockClientRecorder
}

var _ helloclient.Interface = (*MockClient)(nil)

type _MockClientRecorder struct {
	mock *MockClient
}

// Build a new mock client for service Hello.
//
// 	mockCtrl := gomock.NewController(t)
// 	client := hellotest.NewMockClient(mockCtrl)
//
// Use EXPECT() to set expectations on the mock.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &_MockClientRecorder{mock}
	return mock
}

// EXPECT returns an object that allows you to define an expectation on the
// Hello mock client.
func (m *MockClient) EXPECT() *_MockClientRecorder {
	return m.recorder
}

// CallHome responds to a CallHome call based on the mock expectations. This
// call will fail if the mock does not expect this call. Use EXPECT to expect
// a call to this function.
//
// 	client.EXPECT().CallHome(gomock.Any(), ...).Return(...)
// 	... := client.CallHome(...)
func (m *MockClient) CallHome(
	ctx context.Context,
	_CallHome *hello.CallHomeRequest,
	opts ...yarpc.CallOption,
) (success *hello.CallHomeResponse, err error) {

	args := []interface{}{ctx, _CallHome}
	for _, o := range opts {
		args = append(args, o)
	}
	i := 0
	ret := m.ctrl.Call(m, "CallHome", args...)
	success, _ = ret[i].(*hello.CallHomeResponse)
	i++
	err, _ = ret[i].(error)
	return
}

func (mr *_MockClientRecorder) CallHome(
	ctx interface{},
	_CallHome interface{},
	opts ...interface{},
) *gomock.Call {
	args := append([]interface{}{ctx, _CallHome}, opts...)
	return mr.mock.ctrl.RecordCall(mr.mock, "CallHome", args...)
}

// Echo responds to a Echo call based on the mock expectations. This
// call will fail if the mock does not expect this call. Use EXPECT to expect
// a call to this function.
//
// 	client.EXPECT().Echo(gomock.Any(), ...).Return(...)
// 	... := client.Echo(...)
func (m *MockClient) Echo(
	ctx context.Context,
	_Echo *hello.EchoRequest,
	opts ...yarpc.CallOption,
) (success *hello.EchoResponse, err error) {

	args := []interface{}{ctx, _Echo}
	for _, o := range opts {
		args = append(args, o)
	}
	i := 0
	ret := m.ctrl.Call(m, "Echo", args...)
	success, _ = ret[i].(*hello.EchoResponse)
	i++
	err, _ = ret[i].(error)
	return
}

func (mr *_MockClientRecorder) Echo(
	ctx interface{},
	_Echo interface{},
	opts ...interface{},
) *gomock.Call {
	args := append([]interface{}{ctx, _Echo}, opts...)
	return mr.mock.ctrl.RecordCall(mr.mock, "Echo", args...)
}
